TABLE_NAME = "TESTOracleHCMTransactionAuditLogs_CL"
table_body = {
    "properties": {
        "totalRetentionInDays": 30,
        "archiveRetentionInDays": 0,
        "plan": "Analytics",
        "retentionInDaysAsDefault": True,
        "totalRetentionInDaysAsDefault": True,
        "schema": {
            "tableSubType": "Any",
            "name": TABLE_NAME,
            "tableType": "CustomLog",
            "displayName": TABLE_NAME,
            "columns": [
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "DISABLED_FLAG",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "FIRST_CONNECTION",
                    "type": "datetime",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "LANGUAGE_TAG",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "LAST_CONNECTION",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "NLS_LANGUAGE",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "P_USER_NAME",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "RawData",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "SESSION_COOKIE",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "TERRITORY",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "TimeGenerated",
                    "type": "datetime",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "USER_NAME",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "P_FROM_DATE",
                    "type": "string",
                },
                {
                    "description": "",
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "P_TO_DATE",
                    "type": "string",
                },
            ],
            "standardColumns": [
                {
                    "isDefaultDisplay": False,
                    "isHidden": False,
                    "name": "TenantId",
                    "type": "guid",
                }
            ],
            "solutions": ["LogManagement"],
            "isTroubleshootingAllowed": False,
        },
        "provisioningState": "Succeeded",
        "retentionInDays": 30,
    },
    "id": f"/subscriptions/8d29801b-c311-403c-a3c5-80875953c850/resourceGroups/bbw-security-logging-prod-eastus2-rg/providers/Microsoft.OperationalInsights/workspaces/bbw-security-loganalytics-prod-eastus2/tables/{TABLE_NAME}",
    "name": TABLE_NAME,
}
